* cics-crucible condition-handling / hc-named-counters
DEFINE PROGRAM(HCCNTR) GROUP(CRUCHC) LANGUAGE(COBOL)
DEFINE TRANSACTION(HC71) GROUP(CRUCHC) PROGRAM(HCCNTR)
* T001 accepts automatic transaction initiation (START TERMID): SPEC section 2
DEFINE TYPETERM(CRU3278) GROUP(CRUCHC) DEVICE(3270) TERMMODEL(2)
       ATI(YES) TTI(YES)
DEFINE TERMINAL(T001) GROUP(CRUCHC) TYPETERM(CRU3278)
