* cics-crucible condition-handling / hc-inquire-deleteq
DEFINE PROGRAM(HCINQD) GROUP(CRUCHC9) LANGUAGE(COBOL)
DEFINE MAPSET(HCSET2) GROUP(CRUCHC9)
DEFINE TRANSACTION(HC61) GROUP(CRUCHC9) PROGRAM(HCINQD)
DEFINE TRANSACTION(HC62) GROUP(CRUCHC9) PROGRAM(HCINQD)
* T001: ATI/TTI as SPEC section 2 requires
DEFINE TYPETERM(CRU3278) GROUP(CRUCHC9) DEVICE(3270) TERMMODEL(2)
       ATI(YES) TTI(YES)
DEFINE TERMINAL(T001) GROUP(CRUCHC9) TYPETERM(CRU3278)
