* cics-crucible hex-attributes / hx-extended-cursor
DEFINE PROGRAM(HXEXT) GROUP(CRUCHX2) LANGUAGE(COBOL)
DEFINE MAPSET(HXSET2) GROUP(CRUCHX2)
DEFINE TRANSACTION(HX02) GROUP(CRUCHX2) PROGRAM(HXEXT)
DEFINE TYPETERM(CRU3279) GROUP(CRUCHX2) DEVICE(3270) TERMMODEL(2)
       EXTENDEDDS(YES) COLOR(YES) HILIGHT(YES) ATI(YES) TTI(YES)
DEFINE TERMINAL(T001) GROUP(CRUCHX2) TYPETERM(CRU3279)
