* cics-crucible ghost-tasks / gt-terminal-coalesce
DEFINE PROGRAM(GTTERM) GROUP(CRUCGT2) LANGUAGE(COBOL)
DEFINE PROGRAM(GTSHOW) GROUP(CRUCGT2) LANGUAGE(COBOL)
DEFINE TRANSACTION(GT11) GROUP(CRUCGT2) PROGRAM(GTTERM)
DEFINE TRANSACTION(GT12) GROUP(CRUCGT2) PROGRAM(GTSHOW)
