* cics-crucible ghost-tasks / gt-terminal-coalesce
DEFINE PROGRAM(GTTERM) GROUP(CRUCGT2) LANGUAGE(COBOL)
DEFINE PROGRAM(GTSHOW) GROUP(CRUCGT2) LANGUAGE(COBOL)
DEFINE TRANSACTION(GT11) GROUP(CRUCGT2) PROGRAM(GTTERM)
DEFINE TRANSACTION(GT12) GROUP(CRUCGT2) PROGRAM(GTSHOW)
* T001 must accept automatic transaction initiation (START TERMID)
DEFINE TYPETERM(CRU3278) GROUP(CRUCGT2) DEVICE(3270) TERMMODEL(2)
       ATI(YES) TTI(YES)
DEFINE TERMINAL(T001) GROUP(CRUCGT2) TYPETERM(CRU3278)
