* cics-crucible condition-handling / hc-terminal-eoc
DEFINE PROGRAM(HCEOC) GROUP(CRUCHC4) LANGUAGE(COBOL)
DEFINE TRANSACTION(HC04) GROUP(CRUCHC4) PROGRAM(HCEOC)
DEFINE TRANSACTION(HC05) GROUP(CRUCHC4) PROGRAM(HCEOC)
DEFINE TRANSACTION(HC06) GROUP(CRUCHC4) PROGRAM(HCEOC)
* T001 is a 3270 display logical unit (SNA LU type 2): its input is a chain
DEFINE TYPETERM(CRULU2) GROUP(CRUCHC4) DEVICE(LUTYPE2) TERMMODEL(2)
       ATI(YES) TTI(YES)
DEFINE TERMINAL(T001) GROUP(CRUCHC4) TYPETERM(CRULU2)
