* cics-crucible ghost-tasks / gt-urimap-browse
DEFINE PROGRAM(GTUBROW) GROUP(CRUCGT) LANGUAGE(COBOL)
DEFINE PROGRAM(GTUNEXT) GROUP(CRUCGT) LANGUAGE(COBOL)
DEFINE TRANSACTION(GT61) GROUP(CRUCGT) PROGRAM(GTUBROW)
DEFINE TRANSACTION(GT62) GROUP(CRUCGT) PROGRAM(GTUNEXT)
* T001 accepts automatic transaction initiation (START TERMID): SPEC section 2
DEFINE TYPETERM(CRU3278) GROUP(CRUCGT) DEVICE(3270) TERMMODEL(2)
       ATI(YES) TTI(YES)
DEFINE TERMINAL(T001) GROUP(CRUCGT) TYPETERM(CRU3278)
* Four URIMAP definitions, each with an alias transaction. Which of them
* a browse returns first is not stated by IBM: the programs never use the order.
DEFINE URIMAP(ZCONE) GROUP(CRUCGT) USAGE(SERVER) SCHEME(HTTP)
       HOST(*) PATH(/zecs/one) TRANSACTION(GT62) PROGRAM(GTUNEXT)
DEFINE URIMAP(ZCOTHER) GROUP(CRUCGT) USAGE(SERVER) SCHEME(HTTP)
       HOST(*) PATH(/other/x) TRANSACTION(GT62) PROGRAM(GTUNEXT)
DEFINE URIMAP(AAPLAIN) GROUP(CRUCGT) USAGE(SERVER) SCHEME(HTTP)
       HOST(*) PATH(/zecs/plain) TRANSACTION(GT62) PROGRAM(GTUNEXT)
DEFINE URIMAP(BBTHREE) GROUP(CRUCGT) USAGE(SERVER) SCHEME(HTTP)
       HOST(*) PATH(/three) TRANSACTION(GT62) PROGRAM(GTUNEXT)
