* cics-crucible ghost-tasks / gt-send-text-terminal
DEFINE PROGRAM(GTSTXT) GROUP(CRUCGT5) LANGUAGE(COBOL)
DEFINE PROGRAM(GTSTXS) GROUP(CRUCGT5) LANGUAGE(COBOL)
DEFINE TRANSACTION(GT41) GROUP(CRUCGT5) PROGRAM(GTSTXT)
DEFINE TRANSACTION(GT42) GROUP(CRUCGT5) PROGRAM(GTSTXS)
* T001 must accept automatic transaction initiation (START TERMID)
DEFINE TYPETERM(CRU3278) GROUP(CRUCGT5) DEVICE(3270) TERMMODEL(2)
       ATI(YES) TTI(YES)
DEFINE TERMINAL(T001) GROUP(CRUCGT5) TYPETERM(CRU3278)
