* cics-crucible condition-handling / hc-abend-link
DEFINE PROGRAM(HCMAIN) GROUP(CRUCHC2) LANGUAGE(COBOL)
DEFINE PROGRAM(HCSUB) GROUP(CRUCHC2) LANGUAGE(COBOL)
DEFINE TRANSACTION(HC02) GROUP(CRUCHC2) PROGRAM(HCMAIN)
