* cics-crucible commarea-mismatch / ca-xctl-versions
DEFINE PROGRAM(CAXA) GROUP(CRUCCA2) LANGUAGE(COBOL)
DEFINE PROGRAM(CAXB) GROUP(CRUCCA2) LANGUAGE(COBOL)
DEFINE TRANSACTION(CA02) GROUP(CRUCCA2) PROGRAM(CAXA)
DEFINE TRANSACTION(CA03) GROUP(CRUCCA2) PROGRAM(CAXB)
