* cics-crucible condition-handling / hc-eoc-error
DEFINE PROGRAM(HCEOE) GROUP(CRUCHC7) LANGUAGE(COBOL)
DEFINE TRANSACTION(EE01) GROUP(CRUCHC7) PROGRAM(HCEOE)
DEFINE TRANSACTION(EE02) GROUP(CRUCHC7) PROGRAM(HCEOE)
* T001 is a 3270 display logical unit (SNA LU type 2): its input is a chain
DEFINE TYPETERM(CRULU2E) GROUP(CRUCHC7) DEVICE(LUTYPE2) TERMMODEL(2)
       ATI(YES) TTI(YES)
DEFINE TERMINAL(T001) GROUP(CRUCHC7) TYPETERM(CRULU2E)
