* cics-crucible pseudo-conversational / pc-return-immediate
DEFINE PROGRAM(PCIMMA) GROUP(CRUCPC) LANGUAGE(COBOL)
DEFINE PROGRAM(PCIMMB) GROUP(CRUCPC) LANGUAGE(COBOL)
DEFINE PROGRAM(PCIMML) GROUP(CRUCPC) LANGUAGE(COBOL)
DEFINE PROGRAM(PCIMMS) GROUP(CRUCPC) LANGUAGE(COBOL)
DEFINE TRANSACTION(PC51) GROUP(CRUCPC) PROGRAM(PCIMMA)
DEFINE TRANSACTION(PC52) GROUP(CRUCPC) PROGRAM(PCIMMB)
DEFINE TRANSACTION(PC54) GROUP(CRUCPC) PROGRAM(PCIMMS)
* T001 accepts automatic transaction initiation (START TERMID): SPEC section 2
DEFINE TYPETERM(CRU3278) GROUP(CRUCPC) DEVICE(3270) TERMMODEL(2)
       ATI(YES) TTI(YES)
DEFINE TERMINAL(T001) GROUP(CRUCPC) TYPETERM(CRU3278)
