* cics-crucible pseudo-conversational / pc-aid-menu
DEFINE PROGRAM(PCMENU) GROUP(CRUCPC2) LANGUAGE(COBOL)
DEFINE PROGRAM(PCDETL) GROUP(CRUCPC2) LANGUAGE(COBOL)
DEFINE MAPSET(PCSET2) GROUP(CRUCPC2)
DEFINE TRANSACTION(PC11) GROUP(CRUCPC2) PROGRAM(PCMENU)
DEFINE TRANSACTION(PC12) GROUP(CRUCPC2) PROGRAM(PCDETL)
