* cics-crucible pseudo-conversational / pc-wizard
DEFINE PROGRAM(PCWIZ) GROUP(CRUCPC1) LANGUAGE(COBOL)
DEFINE PROGRAM(PCCONF) GROUP(CRUCPC1) LANGUAGE(COBOL)
DEFINE MAPSET(PCSET) GROUP(CRUCPC1)
DEFINE TRANSACTION(PC01) GROUP(CRUCPC1) PROGRAM(PCWIZ)
DEFINE TRANSACTION(PC02) GROUP(CRUCPC1) PROGRAM(PCWIZ)
DEFINE TRANSACTION(PC03) GROUP(CRUCPC1) PROGRAM(PCCONF)
