* cics-crucible ghost-tasks / gt-start-retrieve
DEFINE PROGRAM(GTSTART) GROUP(CRUCGT1) LANGUAGE(COBOL)
DEFINE PROGRAM(GTWORK) GROUP(CRUCGT1) LANGUAGE(COBOL)
DEFINE TRANSACTION(GT01) GROUP(CRUCGT1) PROGRAM(GTSTART)
DEFINE TRANSACTION(GT02) GROUP(CRUCGT1) PROGRAM(GTWORK)
