* cics-crucible condition-handling / hc-resp-options
DEFINE PROGRAM(HCOPT) GROUP(CRUCHC8) LANGUAGE(COBOL)
DEFINE MAPSET(HCSET1) GROUP(CRUCHC8)
DEFINE TRANSACTION(HC51) GROUP(CRUCHC8) PROGRAM(HCOPT)
DEFINE TRANSACTION(HC52) GROUP(CRUCHC8) PROGRAM(HCOPT)
* T001: ATI/TTI as SPEC section 2 requires; UCTRAN(YES) is the terminal's
* UCTRANST, so a RECEIVE MAP without ASIS would upper-case what was typed
DEFINE TYPETERM(CRU3278) GROUP(CRUCHC8) DEVICE(3270) TERMMODEL(2)
       ATI(YES) TTI(YES) UCTRAN(YES)
DEFINE TERMINAL(T001) GROUP(CRUCHC8) TYPETERM(CRU3278)
