* cics-crucible condition-handling / hc-deedit-uctranst
DEFINE PROGRAM(HCDEED) GROUP(CRUCHC4) LANGUAGE(COBOL)
DEFINE TRANSACTION(HC41) GROUP(CRUCHC4) PROGRAM(HCDEED)
* T001: ATI/TTI as SPEC section 2 requires; UCTRAN(YES) is the terminal's
* UCTRANST, stated here so that no port has to guess a default
DEFINE TYPETERM(CRU3278) GROUP(CRUCHC4) DEVICE(3270) TERMMODEL(2)
       ATI(YES) TTI(YES) UCTRAN(YES)
DEFINE TERMINAL(T001) GROUP(CRUCHC4) TYPETERM(CRU3278)
