* cics-crucible commarea-mismatch / ca-channel-containers
DEFINE PROGRAM(CACHAN) GROUP(CRUCCA3) LANGUAGE(COBOL)
DEFINE PROGRAM(CACHSUB) GROUP(CRUCCA3) LANGUAGE(COBOL)
DEFINE PROGRAM(CACHXB) GROUP(CRUCCA3) LANGUAGE(COBOL)
DEFINE PROGRAM(CACHERR) GROUP(CRUCCA3) LANGUAGE(COBOL)
DEFINE TRANSACTION(CA05) GROUP(CRUCCA3) PROGRAM(CACHAN)
DEFINE TRANSACTION(CA06) GROUP(CRUCCA3) PROGRAM(CACHERR)
